name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t flask-stock-app .

    - name: Run Tests Inside Docker Container
      run: |
        docker run -d -p 5000:5000 --env API_KEY="${{ secrets.API_KEY }}" flask-stock-app pytest tests/

    - name: Log in to Docker Hub
      if: success()
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to Registry
      if: success()
      run: |
        docker tag flask-stock-app myatsumon/flask-stock-app:12-17-2024
        docker push myatsumon/flask-stock-app:12-17-2024

    # - name: Run Docker Container
    #   run: |
    #     docker run -d -p 5000:5000 --env API_KEY=${{ secrets.API_KEY }} flask-stock-app
